name: Autograding Tests

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'
 
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-classroom[bot]' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CSS file exists
        id: css-file-exists
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: CSS file exists
          setup-command: ''
          command: test -f assets/css/style.css
          timeout: 10
          max-score: 10

      - name: Custom CSS linked
        id: custom-css-linked
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Custom CSS linked
          setup-command: ''
          command: grep -q "assets/css/style.css" index.html
          timeout: 10
          max-score: 30

      - name: Bootstrap CDN included
        id: bootstrap-cdn-included
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bootstrap CDN included
          setup-command: ''
          command: grep -q "cdn.jsdelivr.net/npm/bootstrap" index.html
          timeout: 10
          max-score: 30

      - name: Navbar present
        id: navbar-present
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Navbar present
          setup-command: ''
          command: grep -q 'class="[^"]*navbar' index.html
          timeout: 10
          max-score: 10

      - name: Contact form present
        id: contact-form-present
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Contact form present
          setup-command: ''
          command: grep -q "<form" index.html
          timeout: 10
          max-score: 20

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          CSS-FILE-EXISTS_RESULTS: "${{ steps.css-file-exists.outputs.result }}"
          CUSTOM-CSS-LINKED_RESULTS: "${{ steps.custom-css-linked.outputs.result }}"
          BOOTSTRAP-CDN-INCLUDED_RESULTS: "${{ steps.bootstrap-cdn-included.outputs.result }}"
          NAVBAR-PRESENT_RESULTS: "${{ steps.navbar-present.outputs.result }}"
          CONTACT-FORM-PRESENT_RESULTS: "${{ steps.contact-form-present.outputs.result }}"
        with:
          runners: css-file-exists,custom-css-linked,bootstrap-cdn-included,navbar-present,contact-form-present
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
